name: Release Jlogg PluginServer

on:
  workflow_dispatch

jobs:
  deploy_package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: >
            [{
              "id":"jlogg",
              "username":"${{secrets.GH_PACKAGES_USERNAME}}"
              "password":"${{secrets.GH_PACKAGES_PASSWORD}}"
            }]
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ github.ref_name }}"
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
